<?php
/**
 * PulseWork (GridCRM) — Server-Side Cron Job Background Worker
 * Handles automated subscription recurring invoicing, dunning escalation for overdue invoices,
 * statutory interest calculations (€40 fee + 10.5% p.a.), and audit logging.
 *
 * Crontab invocation:
 * 0 2 * * * php /path/to/public/api/cron.php --secret=YOUR_CRON_SECRET
 *
 * Compatible with PHP 7.4, 8.0, 8.1, 8.2, 8.3, 8.4+
 */

declare(strict_types=1);

if (!defined('PULSEWORK_DB')) {
    define('PULSEWORK_DB', true);
}

$isCli = (php_sapi_name() === 'cli' || empty($_SERVER['REMOTE_ADDR']));

if (!$isCli) {
    header('Content-Type: application/json; charset=utf-8');
    header('Access-Control-Allow-Origin: *');
    header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
}

require_once __DIR__ . '/db.php';
require_once __DIR__ . '/auth.php';

const BELGIAN_STATUTORY_RECOVERY_FEE = 40.00;
const STATUTORY_LATE_INTEREST_RATE = 0.105; // 10.5% p.a.

// Extract options or CLI flags
$options = $isCli ? getopt('', ['secret::', 'dry-run::', 'force::']) : [];
$dryRun = isset($options['dry-run']) || isset($_GET['dry_run']);
$secretParam = $options['secret'] ?? $_GET['secret'] ?? null;

// Cron execution summary stats
$stats = [
    'startTime' => date('c'),
    'subscriptionsProcessed' => 0,
    'invoicesGenerated' => 0,
    'overdueInvoicesChecked' => 0,
    'dunningNoticesGenerated' => 0,
    'peppolDispatches' => 0,
    'errors' => [],
    'dryRun' => $dryRun,
];

try {
    [$pdo, $engine, $prefix] = getActivePdo();
    ensureAllTables($pdo, $engine, $prefix);

    $todayStr = date('Y-m-d');
    $nowStr = date('Y-m-d H:i:s');
    $nowIso = date('c');

    // ========================================================================
    // Task 1: Subscription Recurring Billing
    // ========================================================================
    $subscriptions = [];
    if ($pdo) {
        $subStmt = $pdo->query("SELECT * FROM `{$prefix}subscriptions`");
        $rawSubs = $subStmt ? $subStmt->fetchAll(\PDO::FETCH_ASSOC) : [];
        foreach ($rawSubs as $r) {
            $decoded = !empty($r['data_json']) ? json_decode($r['data_json'], true) : $r;
            if (is_array($decoded)) {
                $decoded['id'] = $r['id'];
                $subscriptions[] = $decoded;
            }
        }
    } else {
        $store = readJsonStore();
        $subscriptions = $store['subscriptions'] ?? [];
    }

    $createdInvoices = [];
    $updatedSubs = [];

    foreach ($subscriptions as $sub) {
        $status = strtolower((string)($sub['status'] ?? 'active'));
        if ($status !== 'active') continue;

        $nextBillingDate = (string)($sub['nextBillingDate'] ?? $sub['next_billing_date'] ?? '');
        if (empty($nextBillingDate) || $nextBillingDate <= $todayStr) {
            $stats['subscriptionsProcessed']++;

            // Generate structured invoice
            $invId = 'inv_' . bin2hex(random_bytes(6));
            $invNumber = 'INV-' . date('Y') . '-' . str_pad((string)(mt_rand(1000, 9999)), 4, '0', STR_PAD_LEFT);
            $amount = (float)($sub['amount'] ?? $sub['price'] ?? 0);
            $vatRate = (float)($sub['vatRate'] ?? 21.0);
            $vatAmount = round($amount * ($vatRate / 100), 2);
            $totalAmount = $amount + $vatAmount;

            $newInvoice = [
                'id' => $invId,
                'invoiceNumber' => $invNumber,
                'invoice_number' => $invNumber,
                'clientType' => $sub['clientType'] ?? 'company',
                'clientId' => $sub['clientId'] ?? $sub['companyId'] ?? '',
                'clientName' => $sub['clientName'] ?? $sub['customerName'] ?? 'Subscription Customer',
                'issueDate' => $todayStr,
                'dueDate' => date('Y-m-d', strtotime('+30 days')),
                'status' => 'issued',
                'currency' => $sub['currency'] ?? 'EUR',
                'subtotal' => $amount,
                'vatAmount' => $vatAmount,
                'total' => $totalAmount,
                'totalAmount' => $totalAmount,
                'total_amount' => $totalAmount,
                'subscriptionId' => $sub['id'],
                'items' => $sub['items'] ?? [
                    [
                        'id' => 'item_' . uniqid(),
                        'description' => 'Subscription: ' . ($sub['planName'] ?? $sub['name'] ?? 'Recurring Plan'),
                        'quantity' => 1,
                        'unitPrice' => $amount,
                        'vatRate' => $vatRate,
                        'total' => $totalAmount,
                    ]
                ],
                'notes' => 'Automated recurring billing generated by System Worker.',
                'createdAt' => $nowIso,
                'updatedAt' => $nowIso,
                'version' => 1,
            ];

            // Check auto Peppol
            if (!empty($sub['autoSendPeppol']) || !empty($sub['auto_send_peppol'])) {
                $newInvoice['peppolStatus'] = 'queued';
                $stats['peppolDispatches']++;
            }

            $createdInvoices[] = $newInvoice;
            $stats['invoicesGenerated']++;

            // Advance next billing cycle
            $interval = strtolower((string)($sub['interval'] ?? $sub['billingCycle'] ?? 'monthly'));
            $advanceModifier = '+1 month';
            if ($interval === 'quarterly') $advanceModifier = '+3 months';
            elseif ($interval === 'yearly' || $interval === 'annual') $advanceModifier = '+1 year';

            $sub['nextBillingDate'] = date('Y-m-d', strtotime($advanceModifier, strtotime($nextBillingDate ?: $todayStr)));
            $sub['lastBilledDate'] = $todayStr;
            $sub['updatedAt'] = $nowIso;
            $updatedSubs[] = $sub;
        }
    }

    if (!$dryRun) {
        if (!empty($createdInvoices)) {
            if ($pdo) {
                syncGenericTable($pdo, "{$prefix}invoices", $createdInvoices);
                syncGenericTable($pdo, "{$prefix}subscriptions", $updatedSubs);
            } else {
                $store = readJsonStore();
                $store['invoices'] = array_merge($store['invoices'] ?? [], $createdInvoices);
                $store['subscriptions'] = $updatedSubs;
                writeJsonStore($store);
            }
        }
    }

    // ========================================================================
    // Task 2: Dunning Notice Escalation for Overdue Invoices
    // ========================================================================
    $invoices = [];
    if ($pdo) {
        $invStmt = $pdo->query("SELECT * FROM `{$prefix}invoices`");
        $rawInvs = $invStmt ? $invStmt->fetchAll(\PDO::FETCH_ASSOC) : [];
        foreach ($rawInvs as $r) {
            $decoded = !empty($r['data_json']) ? json_decode($r['data_json'], true) : $r;
            if (is_array($decoded)) {
                $decoded['id'] = $r['id'];
                $invoices[] = $decoded;
            }
        }
    } else {
        $store = readJsonStore();
        $invoices = $store['invoices'] ?? [];
    }

    $createdNotices = [];

    foreach ($invoices as $inv) {
        $status = strtolower((string)($inv['status'] ?? 'issued'));
        if (in_array($status, ['paid', 'credited', 'cancelled'], true)) {
            continue;
        }

        $dueDate = (string)($inv['dueDate'] ?? $inv['due_date'] ?? '');
        if (!empty($dueDate) && $dueDate < $todayStr) {
            $stats['overdueInvoicesChecked']++;

            $dueDateTime = strtotime($dueDate);
            $todayTime = strtotime($todayStr);
            $daysOverdue = max(1, (int)round(($todayTime - $dueDateTime) / 86400));

            // Only trigger escalation if overdue by more than 7 days
            if ($daysOverdue >= 7) {
                $originalAmount = (float)($inv['total'] ?? $inv['total_amount'] ?? 0);
                
                // Calculate Belgian Statutory Recovery Fee (€40.00) & Late Interest (10.5% p.a.)
                $statutoryFee = BELGIAN_STATUTORY_RECOVERY_FEE;
                $interestDaysFraction = $daysOverdue / 365.0;
                $calculatedInterest = round($originalAmount * STATUTORY_LATE_INTEREST_RATE * $interestDaysFraction, 2);
                $totalClaim = round($originalAmount + $statutoryFee + $calculatedInterest, 2);

                $stage = 'first_reminder';
                if ($daysOverdue >= 30) $stage = 'formal_notice';
                elseif ($daysOverdue >= 14) $stage = 'second_reminder';

                $noticeId = 'dun_' . bin2hex(random_bytes(6));
                $dunningNotice = [
                    'id' => $noticeId,
                    'invoiceId' => $inv['id'],
                    'invoiceNumber' => $inv['invoiceNumber'] ?? $inv['number'] ?? 'INV',
                    'clientId' => $inv['clientId'] ?? '',
                    'clientName' => $inv['clientName'] ?? 'Client',
                    'daysOverdue' => $daysOverdue,
                    'stage' => $stage,
                    'originalAmount' => $originalAmount,
                    'statutoryFee' => $statutoryFee,
                    'calculatedInterest' => $calculatedInterest,
                    'totalClaim' => $totalClaim,
                    'issuedAt' => $nowIso,
                    'status' => 'queued',
                    'createdAt' => $nowIso,
                ];

                $createdNotices[] = $dunningNotice;
                $stats['dunningNoticesGenerated']++;
            }
        }
    }

    if (!$dryRun && !empty($createdNotices)) {
        if ($pdo) {
            syncGenericTable($pdo, "{$prefix}dunning_notices", $createdNotices);
        } else {
            $store = readJsonStore();
            $store['dunningNotices'] = array_merge($store['dunningNotices'] ?? [], $createdNotices);
            writeJsonStore($store);
        }
    }

    // ========================================================================
    // Task 3: Audit Logging
    // ========================================================================
    $auditSummary = sprintf(
        "Cron completed: %d subscriptions billed (%d invoices), %d overdue checked, %d dunning notices created.",
        $stats['subscriptionsProcessed'],
        $stats['invoicesGenerated'],
        $stats['overdueInvoicesChecked'],
        $stats['dunningNoticesGenerated']
    );

    $auditLogEntry = [
        'id' => 'log_' . bin2hex(random_bytes(8)),
        'timestamp' => $nowStr,
        'actor_name' => 'System Worker (Cron)',
        'action' => 'Automated Background Maintenance',
        'data_json' => json_encode([
            'summary' => $auditSummary,
            'stats' => $stats,
            'executedAt' => $nowIso,
        ], JSON_UNESCAPED_UNICODE),
        'created_at' => $nowStr,
    ];

    if (!$dryRun) {
        if ($pdo) {
            syncGenericTable($pdo, "{$prefix}audit_logs", [$auditLogEntry]);
        } else {
            $store = readJsonStore();
            $store['auditLogs'] = array_merge($store['auditLogs'] ?? [], [$auditLogEntry]);
            writeJsonStore($store);
        }
    }

    $stats['endTime'] = date('c');
    $stats['summary'] = $auditSummary;

    if ($isCli) {
        echo "=== PulseWork CRM Background Cron Worker ===\n";
        echo "Time: " . date('Y-m-d H:i:s') . "\n";
        echo $auditSummary . "\n";
        echo "Status: SUCCESS\n";
    } else {
        sendResponse(true, $auditSummary, ['stats' => $stats]);
    }
} catch (\Throwable $e) {
    $stats['errors'][] = $e->getMessage();
    if ($isCli) {
        fwrite(STDERR, "CRON ERROR: " . $e->getMessage() . "\n");
        exit(1);
    } else {
        sendResponse(false, 'Cron execution failed: ' . $e->getMessage(), ['stats' => $stats], 500);
    }
}
